export const DUMMY_DATA = [
    {
        domain: {
            categoryID: 2,
            categoryName: 'BDC',
            description: null,
            isActive: false,
            isDeleted: false,
            insertedUserID: 0,
            insertedDate: '0001-01-01T00:00:00',
            updatedUserID: 0,
            updatedDate: '0001-01-01T00:00:00',
            insertedUser: null,
            updatedUser: null,
        },
        subDomains: [
            {
                subDomain: {
                    subCategoryID: 2,
                    subCategoryName: 'BDC',
                    description: null,
                    isActive: false,
                    isDeleted: false,
                    insertedUserID: 0,
                    insertedDate: '0001-01-01T00:00:00',
                    updatedUserID: 0,
                    updatedDate: '0001-01-01T00:00:00',
                    insertedUser: null,
                    updatedUser: null,
                },
                mappings: [
                    {
                        mappingId: 1,
                        categoryId: null,
                        subCategoryId: null,
                        description: 'EDI Job',
                        isActive: true,
                        insertedUserId: 0,
                        insertedDate: null,
                        updatedUserId: null,
                        updatedDate: null,
                        isDeleted: null,
                        categoryName: null,
                        subCategoryName: null,
                        insertedUser: null,
                        updatedUser: null,
                    },
                ],
            },
            {
                subDomain: {
                    subCategoryID: 1,
                    subCategoryName: 'BDC',
                    description: null,
                    isActive: false,
                    isDeleted: false,
                    insertedUserID: 0,
                    insertedDate: '0001-01-01T00:00:00',
                    updatedUserID: 0,
                    updatedDate: '0001-01-01T00:00:00',
                    insertedUser: null,
                    updatedUser: null,
                },
                mappings: [
                    {
                        mappingId: 5,
                        categoryId: null,
                        subCategoryId: null,
                        description: 'BDC Jobs',
                        isActive: true,
                        insertedUserId: 0,
                        insertedDate: null,
                        updatedUserId: null,
                        updatedDate: null,
                        isDeleted: null,
                        categoryName: null,
                        subCategoryName: null,
                        insertedUser: null,
                        updatedUser: null,
                    },
                ],
            },
            {
                subDomain: {
                    subCategoryID: 4,
                    subCategoryName: 'BDC',
                    description: null,
                    isActive: false,
                    isDeleted: false,
                    insertedUserID: 0,
                    insertedDate: '0001-01-01T00:00:00',
                    updatedUserID: 0,
                    updatedDate: '0001-01-01T00:00:00',
                    insertedUser: null,
                    updatedUser: null,
                },
                mappings: [
                    {
                        mappingId: 6,
                        categoryId: null,
                        subCategoryId: null,
                        description: 'BDC Sterling Process',
                        isActive: true,
                        insertedUserId: 0,
                        insertedDate: null,
                        updatedUserId: null,
                        updatedDate: null,
                        isDeleted: null,
                        categoryName: null,
                        subCategoryName: null,
                        insertedUser: null,
                        updatedUser: null,
                    },
                ],
            },
        ],
    },
    {
        domain: {
            categoryID: 2,
            categoryName: 'BDC',
            description: null,
            isActive: false,
            isDeleted: false,
            insertedUserID: 0,
            insertedDate: '0001-01-01T00:00:00',
            updatedUserID: 0,
            updatedDate: '0001-01-01T00:00:00',
            insertedUser: null,
            updatedUser: null,
        },
        subDomains: [
            {
                subDomain: {
                    subCategoryID: 2,
                    subCategoryName: 'BDC',
                    description: null,
                    isActive: false,
                    isDeleted: false,
                    insertedUserID: 0,
                    insertedDate: '0001-01-01T00:00:00',
                    updatedUserID: 0,
                    updatedDate: '0001-01-01T00:00:00',
                    insertedUser: null,
                    updatedUser: null,
                },
                mappings: [
                    {
                        mappingId: 1,
                        categoryId: null,
                        subCategoryId: null,
                        description: 'EDI Job',
                        isActive: true,
                        insertedUserId: 0,
                        insertedDate: null,
                        updatedUserId: null,
                        updatedDate: null,
                        isDeleted: null,
                        categoryName: null,
                        subCategoryName: null,
                        insertedUser: null,
                        updatedUser: null,
                    },
                ],
            },
            {
                subDomain: {
                    subCategoryID: 1,
                    subCategoryName: 'BDC',
                    description: null,
                    isActive: false,
                    isDeleted: false,
                    insertedUserID: 0,
                    insertedDate: '0001-01-01T00:00:00',
                    updatedUserID: 0,
                    updatedDate: '0001-01-01T00:00:00',
                    insertedUser: null,
                    updatedUser: null,
                },
                mappings: [
                    {
                        mappingId: 5,
                        categoryId: null,
                        subCategoryId: null,
                        description: 'BDC Jobs',
                        isActive: true,
                        insertedUserId: 0,
                        insertedDate: null,
                        updatedUserId: null,
                        updatedDate: null,
                        isDeleted: null,
                        categoryName: null,
                        subCategoryName: null,
                        insertedUser: null,
                        updatedUser: null,
                    },
                ],
            },
            {
                subDomain: {
                    subCategoryID: 4,
                    subCategoryName: 'BDC',
                    description: null,
                    isActive: false,
                    isDeleted: false,
                    insertedUserID: 0,
                    insertedDate: '0001-01-01T00:00:00',
                    updatedUserID: 0,
                    updatedDate: '0001-01-01T00:00:00',
                    insertedUser: null,
                    updatedUser: null,
                },
                mappings: [
                    {
                        mappingId: 6,
                        categoryId: null,
                        subCategoryId: null,
                        description: 'BDC Sterling Process',
                        isActive: true,
                        insertedUserId: 0,
                        insertedDate: null,
                        updatedUserId: null,
                        updatedDate: null,
                        isDeleted: null,
                        categoryName: null,
                        subCategoryName: null,
                        insertedUser: null,
                        updatedUser: null,
                    },
                ],
            },
        ],
    },
    {
        domain: {
            categoryID: 2,
            categoryName: 'BDC',
            description: null,
            isActive: false,
            isDeleted: false,
            insertedUserID: 0,
            insertedDate: '0001-01-01T00:00:00',
            updatedUserID: 0,
            updatedDate: '0001-01-01T00:00:00',
            insertedUser: null,
            updatedUser: null,
        },
        subDomains: [
            {
                subDomain: {
                    subCategoryID: 2,
                    subCategoryName: 'BDC',
                    description: null,
                    isActive: false,
                    isDeleted: false,
                    insertedUserID: 0,
                    insertedDate: '0001-01-01T00:00:00',
                    updatedUserID: 0,
                    updatedDate: '0001-01-01T00:00:00',
                    insertedUser: null,
                    updatedUser: null,
                },
                mappings: [
                    {
                        mappingId: 1,
                        categoryId: null,
                        subCategoryId: null,
                        description: 'EDI Job',
                        isActive: true,
                        insertedUserId: 0,
                        insertedDate: null,
                        updatedUserId: null,
                        updatedDate: null,
                        isDeleted: null,
                        categoryName: null,
                        subCategoryName: null,
                        insertedUser: null,
                        updatedUser: null,
                    },
                ],
            },
            {
                subDomain: {
                    subCategoryID: 1,
                    subCategoryName: 'BDC',
                    description: null,
                    isActive: false,
                    isDeleted: false,
                    insertedUserID: 0,
                    insertedDate: '0001-01-01T00:00:00',
                    updatedUserID: 0,
                    updatedDate: '0001-01-01T00:00:00',
                    insertedUser: null,
                    updatedUser: null,
                },
                mappings: [
                    {
                        mappingId: 5,
                        categoryId: null,
                        subCategoryId: null,
                        description: 'BDC Jobs',
                        isActive: true,
                        insertedUserId: 0,
                        insertedDate: null,
                        updatedUserId: null,
                        updatedDate: null,
                        isDeleted: null,
                        categoryName: null,
                        subCategoryName: null,
                        insertedUser: null,
                        updatedUser: null,
                    },
                ],
            },
            {
                subDomain: {
                    subCategoryID: 4,
                    subCategoryName: 'BDC',
                    description: null,
                    isActive: false,
                    isDeleted: false,
                    insertedUserID: 0,
                    insertedDate: '0001-01-01T00:00:00',
                    updatedUserID: 0,
                    updatedDate: '0001-01-01T00:00:00',
                    insertedUser: null,
                    updatedUser: null,
                },
                mappings: [
                    {
                        mappingId: 6,
                        categoryId: null,
                        subCategoryId: null,
                        description: 'BDC Sterling Process',
                        isActive: true,
                        insertedUserId: 0,
                        insertedDate: null,
                        updatedUserId: null,
                        updatedDate: null,
                        isDeleted: null,
                        categoryName: null,
                        subCategoryName: null,
                        insertedUser: null,
                        updatedUser: null,
                    },
                ],
            },
        ],
    },
]
